name: Tests
on:
  push:
    branches: [master, r0.9]
jobs:
  linux:
    strategy:
      matrix:
        python-version: [3.9.x, 3.10.x]
        platform: [ubuntu-latest]
    runs-on: ${{matrix.platform}}
    steps:
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: python --version
